In [1]:
import torch
import numpy as np

In [2]:
y = [4.209015  , 6.0251656 , 6.586659  , 1.0785204 , 5.323591,   2.9644287, 8.885769  , 9.895647  ,  6.464806  , 0.18034637, 1.2534696]
x = [34.552039 , 74.45411  , 80.987488 ,  3.458197 , 56.4778655, 26.98163  , 95.79415  , 106.228316 , 61.169422 , 1.089516 , 8.962632]

In [3]:
y = torch.tensor(y)
x = torch.tensor(x)
x

tensor([ 34.5520,  74.4541,  80.9875,   3.4582,  56.4779,  26.9816,  95.7942,
        106.2283,  61.1694,   1.0895,   8.9626])

In [4]:
def model(x, w, b):
    return w * x + b

In [5]:
def loss_fn(yy, y):
    squared_diffs = (yy - y)**2
    return squared_diffs.mean()

In [6]:
import torch.optim as optim
dir(optim)

['ASGD',
 'Adadelta',
 'Adagrad',
 'Adam',
 'AdamW',
 'Adamax',
 'LBFGS',
 'Optimizer',
 'RMSprop',
 'Rprop',
 'SGD',
 'SparseAdam',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_multi_tensor',
 'functional',
 'lr_scheduler',
 'swa_utils']

In [7]:
params = torch.tensor([1.0, 0.0], requires_grad=True)
learning_rate = 1e-5
optimizer = optim.SGD([params], lr=learning_rate)

In [8]:
yy = model(x, *params)
loss = loss_fn(yy, y)
loss.backward()
optimizer.step()

params

tensor([ 9.3147e-01, -9.0416e-04], requires_grad=True)

In [9]:
x_u = x * 0.1
params = torch.tensor([1.0, 0.0], requires_grad=True)
learning_rate = 1e-2
optimizer = optim.SGD([params], lr=learning_rate)
yy = model(x_u, *params)
loss = loss_fn(yy, y)
optimizer.zero_grad()
loss.backward()
optimizer.step()
params

tensor([ 0.9400, -0.0039], requires_grad=True)

In [10]:
def training_loop(n_epochs, optimizer, params, x, y):
    for epoch in range(1, n_epochs + 1):
        yy = model(x, *params)
        loss = loss_fn(yy, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if epoch % 500 == 0:
            print('Epoch %d, Loss %f' % (epoch, float(loss)))
    return params

In [11]:
params = torch.tensor([1.0, 0.0], requires_grad=True)
learning_rate = 1e-2
optimizer = optim.SGD([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    x = x_u,
    y = y)

Epoch 500, Loss 0.263147
Epoch 1000, Loss 0.262983
Epoch 1500, Loss 0.262982
Epoch 2000, Loss 0.262982
Epoch 2500, Loss 0.262982
Epoch 3000, Loss 0.262982
Epoch 3500, Loss 0.262982
Epoch 4000, Loss 0.262982
Epoch 4500, Loss 0.262982
Epoch 5000, Loss 0.262982


tensor([0.8410, 0.5997], requires_grad=True)

In [12]:
params = torch.tensor([1.0, 0.0], requires_grad=True)
learning_rate = 1e-1
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    x = x,
    y = y)

Epoch 500, Loss 0.265097
Epoch 1000, Loss 0.262982
Epoch 1500, Loss 0.262982
Epoch 2000, Loss 0.262982
Epoch 2500, Loss 0.262983
Epoch 3000, Loss 0.262982
Epoch 3500, Loss 0.262982
Epoch 4000, Loss 0.262982
Epoch 4500, Loss 0.262982
Epoch 5000, Loss 0.262982


tensor([0.0841, 0.5997], requires_grad=True)